services: 
  backend:
    depends_on:
      - db
    build:
      .
    ports:
      - 7150:80
  
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: 787898
      POSTGRES_USER: aloshaprokopenko5
      POSTGRES_DB: WebPortalDb

 # proxy:
   # image: nginx:mainline
   # volumes:
   #   - ./nginx.conf:/etc/nginx/nginx.conf
   # ports:
    #  - 8081:8002

  #frontend:
   # image: olexiypr/frontend
   # build:
   #   ./../../../WebstormProjects/WebPortal.Frontend/
   # ports:
   #   - 8001:80
      
        
